Added simple scheduled task code
krvikas1011/LLD-Examples pull request #7
Opened 2022-03-29 16:56 UTC by shubhaangi04

2022-03-29 16:57 UTC, shubhaangi04 commented
Related to #4

2022-03-29 16:59 UTC, krvikas1011 requested changes

2022-03-29 16:59 UTC, krvikas1011 commented on Beginner/SimpleScheduledTask/src/main/java/SimpleScheduler.java
> +
remove empty space

2022-03-30 05:47 UTC, krvikas1011 requested changes

2022-03-30 05:47 UTC, krvikas1011 commented on Beginner/SimpleScheduledTask/src/main/java/SimpleScheduler.java
> +        }
why is this logic in the main method??

2022-03-30 06:24 UTC, krvikas1011 approved these changes

2022-03-30 06:24 UTC, merged